application: your-app-engine-application-name-goes-here
version: 1
runtime: python
api_version: 1

derived_file_type:
- python_precompiled

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  script: fonts.py